import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def _send(to_email: str, subject: str, html: str) -> None:
    smtp_host = os.environ.get('SMTP_HOST', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('SMTP_PORT', 587))
    smtp_user = os.environ.get('SMTP_USER')
    smtp_pass = os.environ.get('SMTP_PASSWORD')

    if not smtp_user or not smtp_pass:
        print('[Email] SMTP credentials not set — skipping.')
        return

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = smtp_user
    msg['To'] = to_email
    msg.attach(MIMEText(html, 'html'))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, to_email, msg.as_string())

    print(f'[Email] Sent to {to_email}: {subject}')


def send_completion_email(to_email, sheet_url, platform, location, count):
    subject = f'✅ Scraping done — {count} restaurants from {location} ({platform.capitalize()})'
    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:24px;">
      <h2 style="color:#009de0;">🍽️ Your restaurant data is ready!</h2>
      <p>The scraping job completed successfully.</p>
      <table style="border-collapse:collapse;margin:16px 0;">
        <tr><td style="padding:6px 12px;background:#f4f6fb;font-weight:bold;">Platform</td>
            <td style="padding:6px 12px;">{platform.capitalize()}</td></tr>
        <tr><td style="padding:6px 12px;background:#f4f6fb;font-weight:bold;">Location</td>
            <td style="padding:6px 12px;">{location}</td></tr>
        <tr><td style="padding:6px 12px;background:#f4f6fb;font-weight:bold;">Restaurants</td>
            <td style="padding:6px 12px;"><strong>{count}</strong></td></tr>
      </table>
      <a href="{sheet_url}" style="display:inline-block;padding:14px 28px;background:#10b981;
         color:#fff;text-decoration:none;border-radius:8px;font-weight:bold;font-size:1rem;">
        📊 Open Google Sheet
      </a>
      <p style="margin-top:24px;color:#6b7280;font-size:0.85rem;">
        Anyone with the link can view the sheet.<br/>Generated by Restaurant Scraper.
      </p>
    </body></html>
    """
    _send(to_email, subject, html)


def send_error_email(to_email, platform, location, error_message):
    subject = f'❌ Scraping failed — {platform.capitalize()} / {location}'
    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;padding:24px;">
      <h2 style="color:#ef4444;">❌ Scraping stopped due to an error</h2>
      <p>An error occurred and the scraping job was stopped automatically.</p>
      <table style="border-collapse:collapse;margin:16px 0;">
        <tr><td style="padding:6px 12px;background:#fff5f5;font-weight:bold;">Platform</td>
            <td style="padding:6px 12px;">{platform.capitalize()}</td></tr>
        <tr><td style="padding:6px 12px;background:#fff5f5;font-weight:bold;">Location</td>
            <td style="padding:6px 12px;">{location}</td></tr>
        <tr><td style="padding:6px 12px;background:#fff5f5;font-weight:bold;">Error</td>
            <td style="padding:6px 12px;color:#ef4444;"><code>{error_message}</code></td></tr>
      </table>
      <p style="color:#6b7280;font-size:0.85rem;">
        Please try again or contact support if the issue persists.<br/>
        Generated by Restaurant Scraper.
      </p>
    </body></html>
    """
    _send(to_email, subject, html)
