"""
Email notification service using Gmail SMTP (or any SMTP provider).

Setup:
  Set these env vars:
    SMTP_HOST     — e.g. smtp.gmail.com
    SMTP_PORT     — e.g. 587
    SMTP_USER     — your Gmail address
    SMTP_PASSWORD — Gmail App Password (not your main password)
                    Create at: https://myaccount.google.com/apppasswords
"""
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_completion_email(
    to_email: str,
    sheet_url: str,
    platform: str,
    location: str,
    count: int,
) -> None:
    smtp_host = os.environ.get('SMTP_HOST', 'smtp.gmail.com')
    smtp_port = int(os.environ.get('SMTP_PORT', 587))
    smtp_user = os.environ.get('SMTP_USER')
    smtp_pass = os.environ.get('SMTP_PASSWORD')

    if not smtp_user or not smtp_pass:
        print('[Email] SMTP credentials not set — skipping email notification.')
        return

    subject = f'✅ Scraping done — {count} restaurants from {location} ({platform.capitalize()})'

    html = f"""
    <html><body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
      <h2 style="color: #009de0;">🍽️ Your restaurant data is ready!</h2>
      <p>The scraping job has completed successfully.</p>
      <table style="border-collapse: collapse; margin: 16px 0;">
        <tr><td style="padding: 6px 12px; background:#f4f6fb; font-weight:bold;">Platform</td>
            <td style="padding: 6px 12px;">{platform.capitalize()}</td></tr>
        <tr><td style="padding: 6px 12px; background:#f4f6fb; font-weight:bold;">Location</td>
            <td style="padding: 6px 12px;">{location}</td></tr>
        <tr><td style="padding: 6px 12px; background:#f4f6fb; font-weight:bold;">Restaurants found</td>
            <td style="padding: 6px 12px;"><strong>{count}</strong></td></tr>
      </table>
      <a href="{sheet_url}"
         style="display:inline-block; padding: 14px 28px; background:#10b981; color:#fff;
                text-decoration:none; border-radius:8px; font-weight:bold; font-size:1rem;">
        📊 Open Google Sheet
      </a>
      <p style="margin-top:24px; color:#6b7280; font-size:0.85rem;">
        This link is shareable — anyone with the link can view the sheet.<br/>
        Generated by Restaurant Scraper.
      </p>
    </body></html>
    """

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = smtp_user
    msg['To'] = to_email
    msg.attach(MIMEText(html, 'html'))

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, to_email, msg.as_string())

    print(f'[Email] Sent completion email to {to_email}')
